### ISSUE TITLE
No more works

### ISSUE THREAD

**Issue by hafuz** [olear/audiocurve#10]
Hi,
Last time i had used audiocurve, it works.
I need to reopen some  projects create in snapshots some months ago,which work perfectly, but now i get errors in the script editor:

```
Failed to execute onParamChanged callback: While executing script:
AudioCurve.paramHasChanged(app1.AudioCurve1.atFrameNum,app1.AudioCurve1,app1,app1,False)
Python error:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/hafuz/.Natron/Plugins/AudioCurve.py", line 105, in paramHasChanged
    if ascii_file is not None and audio_file is not None and thisParam == thisNode.importCurve:
AttributeError: 'NatronEngine.Effect' object has no attribute 'importCurve'
```

**Comment by olear** [comment]
Hi,

I will check if this is a bug in Natron, or if the API changed. Will try to fix as soon as possible. 

Thanks for reporting the issue.

**Comment by olear** [comment]
Should work in next Natron release, 2.0.2.
